name: Actions

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

  publish:
    needs: build
    name: publish-job
    runs-on: ubuntu-latest
    steps:
      # Download Artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: build
          
      - name: Install Official Butler CLI
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler-cli
          chmod +x butler-cli/butler
          sudo mv butler-cli/butler /usr/local/bin/
          rm -rf butler-cli butler.zip

      - name: Verify Butler Installation
        run: butler -V

      - name: Push Build to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_BUTLER_API_KEY }}
        run: |
          butler push build/WebGL ${{ env.ITCH_USERNAME }}/${{ env.ITCH_GAME_ID }}:webgl


